- type: random
  prefix:
  choices:
    - The FCC should safeguard Internet freedom by keeping the bright-line net neutrality protections in place and upholding Title II.
    - We need the FCC to defend the rights of millions of Internet users by upholding net neutrality protections.
    - I’m calling on the FCC to stand up for net neutrality and safeguard Title II protections.
    - The FCC should ensure a fair and open Internet for all by opposing efforts to undermine net neutrality.
    - The FCC should stand up for Internet users by safeguarding net neutrality.
    - The FCC must protect the open Internet by maintaining net neutrality protections under Title II.
    - As an Internet user, I’m asking the FCC to protect the net neutrality protections currently in place.
    - The FCC needs to stand up for Internet users like me and keep the net neutrality rules that are already in effect.

- type: break

- type: random
  prefix: The FCC should
  choices:
    - reject
    - throw out

- type: random
  prefix: Chairman Ajit Pai’s
  choices:
    - plan
    - proposal

- type: random
  prefix: to
  choices:
    - give
    - hand

- type: random
  prefix:
  choices:
    - the
    - the government-subsidized

- type: random
  prefix:
  choices:
    - telecom giants
    - ISP monopolies

- type: random
  prefix: like
  choices:
    - Comcast, AT&T, and Verizon
    - AT&T, Comcast, and Verizon
    - Comcast,  Verizon, and AT&T
    - AT&T, Verizon, and Comcast
    - Verizon,  AT&T, and Comcast
    - Verizon, Comcast, and AT&T

- type: random
  prefix:
  choices:
    - free rein to
    - the authority to
    - the legal cover to

- type: random
  prefix:
  choices:
    - engage in data discrimination,
    - throttle whatever they please,
    - create Internet fast lanes,

- type: random
  prefix: stripping
  choices:
    - consumers
    - users
    - Internet users

- type: random
  prefix: of the
  choices:
    - necessary
    - meaningful
    - vital

- type: random
  prefix:
  choices:
    - access and privacy
    - privacy and access

- type: random
  prefix:
  choices:
    - protections
    - rules
    - safeguards

- type: random
  prefix: we
  choices:
    - fought for
    - demanded
    - worked for

- type: random
  prefix: and
  choices:
    - won just two years ago.
    - just recently won.
    - so recently won.

- type: break

- type: random
  prefix:
  choices:
    - I’m worried about creating a tiered Internet with “fast lanes” for certain sites or services because
    - I’m concerned about ISPs being allowed to discriminate against certain types of data or websites because
    - I’m afraid of a “pay-to-play” Internet where ISPs can charge more for certain websites because

# this one really should have Other...
- type: user-select-or-other
  prefix:
  choices:
    - Users will have fewer options and a less diverse Internet.
    - ISPs could have too much power to determine what I can do online.

- type: random
  prefix: Thankfully, the
  choices:
    - current
    - existing

- type: random
  prefix:
  choices:
    - net neutrality rules
    - FCC regulations
    - Open Internet rules

- type: random
  prefix:
  choices:
    - ensure that
    - mean that

- type: random
  prefix:
  choices:
    - ISPs
    - Internet providers
    - ISP monopolies

- type: random
  prefix: can’t
  choices:
    - block or slow
    - slow or block

- type: random
  prefix:
  choices:
    - customers’
    - our
    - users’
    - Internet users’
    - consumers’

- type: random
  prefix:
  choices:
    - access to
    - ability to see

- type: random
  prefix: certain
  choices:
    - websites or
    - web services or


- type: random
  prefix:
  choices:
    - create Internet “fast lanes”
    - engage in data discrimination

- type: random
  prefix: by charging
  choices:
    - websites and online service
    - online services and websites

- type: random
  prefix:
  choices:
    - money
    - more money

- type: random
  prefix: to reach
  choices:
    - consumers
    - customers
    - people

- type: random
  prefix: faster.
  choices:
    - That’s exactly the right balance
    - That’s the best way forward
    - That’s the right kind of forward-looking approach

- type: random
  prefix: to
  choices:
    - ensure the Internet remains a level playing field that
    - make sure competition in the Internet space is fair and
    - 

- type: random
  prefix: benefits
  choices:
    - consumers and small businesses
    - small businesses and consumers
    - Internet users and small businesses
    - small businesses and Internet users

- type: random
  prefix: as well as
  choices:
    - larger players.
    - entrenched Internet companies.

- type: random
  prefix: 
  choices:
    - Pai’s
    - Chairman Pai’s

- type: random
  prefix: 
  choices:
    - proposal
    - proposed repeal of the rules

- type: random
  prefix: would
  choices:
    - help turn
    - transform

- type: random
  prefix: 
  choices:
    - ISPs
    - Internet providers

- type: random
  prefix: into
  choices:
    - gatekeepers
    - Internet gatekeepers

- type: random
  prefix: with
  choices:
    - an effective veto right on
    - the ability to veto new

- type: random
  prefix: 
  choices:
    - innovation and expression.
    - expression and innovation.

- type: random
  prefix: 
  choices:
    - That’s not how the Internet was built, and that not what we want.
    - That’s not the kind of Internet we want to pass on to future generations of technology users.
    - That’s contrary to the basic precepts on which the Internet was built.

- type: break

- type: freeform
  prompt: "Why the internet matters to me:"

- type: break

- type: random
  prefix: 
  choices:
    - Thank you for keeping Title II net neutrality rules in place to protect Internet users like me.
    - I urge you to keep Title II net neutrality in place, and safeguard Internet users like me.
    - Thanks for protecting Internet users like me by upholding the existing Title II net neutrality rules.
    - I appreciate you maintaining Title II net neutrality rules and the rights of Internet users like me.

